### PR TITLE
Update dependencies to fix critical issues

### PR DESCRIPTION
**Pull request by jessb321**
Fixes security flaw in electron-packager.

### CODE REVIEW

**Comment by azu** [comment]
> This module requires Node.js 4.0 or higher to run.
> https://github.com/electron-userland/electron-packager#installation

electron-packger requires Node.js 4.0 or higher and need to update `.travis.yml`.

**Comment by jessb321** [comment]
Whoops, must've not been committed, that should fix it.

**Comment by jessb321** [comment]
Okay, there we go, build passed. Thanks for the prompt reply btw.

**Comment by azu** [comment]
@willyb321 Thanks for quick fix!

**Comment by jessb321** [comment]
@azu and thank you for merging, and also making it!

**Comment by azu** [comment]
Release https://github.com/azu/electron-zip-packager/releases/tag/2.0.0

**Pull request merged**
